version: "3.8"

services:
  crawler:
    container_name: crawler
    build:
      context: crawler
    env_file:
      - crawler/.env.container
    networks:
      - crawler
  consumer:
    container_name: consumer
    build:
      context: consumer
    env_file:
      - consumer/.env.container
    networks:
      - crawler

networks:
  crawler:
    external: true