version: "3.8"

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.95.0
    volumes:
      - ./configs/otelcol/config.yaml:/etc/otelcol/config.yaml
    ports:
      - 4317:4317 # GRPC
      - 4318:4318 # HTTP
  jaeger:
    image: jaegertracing/all-in-one:1.54.0
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    ports:
      - 16686:16686
  tempo:
    image: grafana/tempo:main-3738ab8
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./configs/tempo/config.yaml:/etc/tempo.yaml
      - ./tempo:/tmp/tempo
    ports:
      - 3200:3200
  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - 3100:3000