name: CI

# Cancel previous runs that are not completed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  actions: read

jobs:
  cd:
    name: SSH to server and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 080196/crawler-website
          tags: |
            type=raw,value={{date 'YYYY-MM-DD'}}

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIV_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/crawler-demo
            sh deploy.sh 080196/crawler-website ${{ steps.meta.outputs.tags }}

      # - name: Setup SSH
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts

      # - name: Deploy
      #   run: |
      #     rsync -avz -e deploy.sh ubuntu@${{ secrets.USER_IP }}:/home/ubuntu/crawler-demo/deploy.sh --delete --force
      #     ssh ubuntu@${{ secrets.USER_IP }} <<EOF
      #       cd /home/ubuntu/crawler-demo
      #       sudo chmod +x deploy.sh
      #       sh deploy.sh 080196/crawler-website ${{ env.SHORT_SHA }}
      #     EOF